# Generated by Django 4.2.7 on 2024-03-02 16:52

from django.db import migrations, models
import django.db.models.deletion
import wounddetection.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WoundInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('diameter', models.CharField(max_length=30)),
                ('additional', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.patient')),
                ('wound_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.woundinfo')),
            ],
        ),
    ]
