# Generated by Django 4.2.7 on 2024-03-10 09:36

from django.db import migrations, models
import django.db.models.deletion
import wounddetection.models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('depth', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('diameter', models.CharField(max_length=30)),
                ('additional', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.case')),
            ],
        ),
        migrations.DeleteModel(
            name='Wound',
        ),
        migrations.DeleteModel(
            name='WoundInfo',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.specialization'),
        ),
        migrations.AddField(
            model_name='case',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wounddetection.patient'),
        ),
    ]
