# Generated by Django 4.2.7 on 2024-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0003_remove_woundreport_case_case_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundreport',
            name='image_url',
            field=models.CharField(max_length=100),
        ),
    ]
