# Generated by Django 4.2.7 on 2024-03-10 13:57

from django.db import migrations, models
import wounddetection.models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0004_alter_woundreport_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundreport',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=wounddetection.models.upload_to),
        ),
    ]
