# Generated by Django 4.2.7 on 2024-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0005_alter_woundreport_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundreport',
            name='upload_date',
            field=models.DateTimeField(null=True),
        ),
    ]
