# Generated by Django 4.2.7 on 2024-03-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0006_alter_woundreport_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='noname', max_length=30),
            preserve_default=False,
        ),
    ]
