# Generated by Django 4.2.7 on 2024-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0007_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reports',
            field=models.ManyToManyField(blank=True, to='wounddetection.woundreport'),
        ),
    ]
