# Generated by Django 4.2.7 on 2024-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0009_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='reports',
            field=models.ManyToManyField(to='wounddetection.woundreport'),
        ),
    ]
