# Generated by Django 4.2.7 on 2024-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wounddetection', '0010_alter_case_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='cases',
            field=models.ManyToManyField(to='wounddetection.case'),
        ),
    ]
